"""
build_feature_matrix_cache.py
Builds the feature matrix from the cached cohort and saves it for reuse
by ablation and sensitivity analyses.

Usage:
    python new_analyses/build_feature_matrix_cache.py

Requires: ml/cache/cohort_h24_w6.pkl (generated by first training run)
Output:   new_analyses/feature_matrix.parquet
"""

import logging
import pickle
import sys
from pathlib import Path

logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)-8s %(message)s", datefmt="%H:%M:%S")
log = logging.getLogger(__name__)

# Add ml/ to path for imports
ml_dir = Path(__file__).resolve().parent.parent / "ml"
sys.path.insert(0, str(ml_dir))

from feature_engineering import build_feature_matrix, get_feature_columns

cohort_path = ml_dir / "cache" / "cohort_h24_w6.pkl"
out_path = Path(__file__).resolve().parent / "feature_matrix.parquet"

if out_path.exists():
    log.info(f"Feature matrix already exists at {out_path}")
    import pandas as pd
    df = pd.read_parquet(out_path)
    log.info(f"  Shape: {df.shape}")
    log.info(f"  Columns: {len(df.columns)}")
    log.info(f"  Label prevalence: {df['label'].mean():.4f}")
    sys.exit(0)

log.info(f"Loading cohort from {cohort_path}...")
with open(cohort_path, "rb") as f:
    cohort = pickle.load(f)

log.info(f"  Windows: {len(cohort['windows']):,}")
log.info(f"  Vitals: {len(cohort['vitals']):,}")
log.info(f"  Labs: {len(cohort['labs']):,}")

log.info("Building feature matrix (this may take 30-60 minutes)...")
df = build_feature_matrix(
    cohort=cohort,
    horizon_hours=24,
    window_hours=6.0,
)

# Drop windows with no vitals
vital_cols = ["heart_rate", "systolic_bp", "spo2", "respiratory_rate", "temperature"]
vital_present = [c for c in vital_cols if c in df.columns]
df = df.dropna(subset=vital_present, how="all")

log.info(f"Final feature matrix: {len(df):,} rows, {len(df.columns)} columns")
log.info(f"Label prevalence: {df['label'].mean():.4f}")

log.info(f"Saving to {out_path}...")
df.to_parquet(out_path, index=False)
log.info("Done.")
